baseURL = 'https://xiaogoulingdi.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
mainSections = ["life"]
[params]
    title = "xiaogoulingdi"
    author = "小狗领地"
    description = "为了寻找你我搬进鸟的眼睛，经常盯着路过的风，很高兴遇见你！"
    email = "wuhaoyang807@gmail.com"
    profilePicture = "/image/user_image.jpg"

[[params.socialIcons]]

    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/xiaogoulingdi"

[[params.socialIcons]]
  icon  = "fas fa-envelope"
  title = "Email"
  url   = "mailto:wuhaoyang807@gmail.com"

[taxonomy]
    category = "categories"
    tag = "tages"
[menu]
    [[menu.main]]
    identifier = "hone"
    name = "首页"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

    [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
